import { Link } from "react-router-dom";
import { Home as HomeIcon } from "lucide-react"; 
import "./Page2.css";

export function Page2() {
  return (
    <div className="page2-container">
      {/* Icono Home */}
      <div className="home-icon">
        <Link to="/">
          <HomeIcon size={28} />
        </Link>
      </div>

      <h4 className="page2-title">About This App</h4>

      <div className="page2-block">
        <p>
          <strong>Developed by:</strong> Diego Da Rocha — 2025 🛠️
        </p>

        <h5>Instructions 📋</h5>
        <ul className="checklist">
          <li>Upload a photo of a dish and click <strong>Select Image</strong> to get a recipe generated by AI.</li>
          <li>Wait for the recipe to be processed (complex dishes may take longer).</li>
        </ul>

        <h5>Technology Stack 💻</h5>
        <ul className="techlist">
          <li>React</li>
          <li>Backendless (backend service)</li>
          <li>Flowrunner (automation flows)</li>
          <li>Personalized AI assistant</li>
          <li>Modern JavaScript tools</li>
        </ul>

        <h5>Notes ℹ️</h5>
        <ul className="noteslist">
          <li>This is a free-access showcase application designed for demonstration and learning purposes.</li>
          <li>It is not intended for production environments.</li>
          <li>Feedback and suggestions are always welcome 🙌 — the goal is to inspire people with creative recipes from food photos.</li>
        </ul>
      </div>

      <footer className="page2-footer">© 2025 Diego Da Rocha — Demo App</footer>
    </div>
  );
}
